### ISSUE TITLE
Don't override ctrl+` and ctrl+shift+` keybindings

### ISSUE THREAD

**Issue by Tyriar** [joshbax-msft/mdhelper#1]
This overrides the fairly well known/common keybindings to toggle the integrated terminal, essentially hiding the feature. It's probably best you don't do that :smile: 

There was a report on Microsoft/vscode about this https://github.com/Microsoft/vscode/issues/19742

**Comment by joshbax-msft** [comment]
It also helps if I pay attention to this project more than once a year. Thanks for catching this. I'll look into adding shift or alt, if those don't override other commands.

**Comment by joshbax-msft** [comment]
https://github.com/joshbax-msft/mdhelper/commit/9271e2f54bdb96c7f51690594beb8b5307ded616

Replaced inline code with Alt+\`
Replaced code block with Alt+Shift+\`

Published to Marketplace as v0.0.10

Thanks!

**Comment by Tyriar** [comment]
Great :smiley:
