### ISSUE TITLE
Only apply keybindings within Markdown files

### ISSUE THREAD

**Issue by Tyriar** [joshbax-msft/mdhelper#2]
You can apply keybindings only when you're editing a markdown file, this might be useful. Example from default keybindings:

```js
{ "key": "ctrl+k ctrl+k",         "command": "editor.action.defineKeybinding",
                                     "when": "editorTextFocus && !editorReadonly && editorLangId == 'json'" },
```

**Comment by joshbax-msft** [comment]
Thanks for this one, as well. I had someone submit a pull request to add this. I'll verify soon and close this out.

**Comment by joshbax-msft** [comment]
All set. Thanks again.
